title:        Ali Ghazi
tagline:      'Ali Ghazi - Software Developer'
description:  'My "Professional Website"'
url:          http://alighazi.github.io
version:      1.1.1
author:
  name:       'Ali Ghazi'
  email:      'ali.msgh@gmail.com'
markdown:     redcarpet
permalink:    pretty
pygments:     true
paginate:     5
