title:        Ali Ghazi
tagline:      'Software Developer & Designer'
description:  'Software developer running <a href="ekiper.net" target="_blank">ekiper.net</a>.'
url:          http://andhyde.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     redcarpet
permalink:    pretty
pygments:     true
paginate:     5
host: localhost